// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --import tsx prisma/seed.ts",
  },
  datasource: {
    // Prefer DIRECT_URL for migrate/introspect so commands bypass any
    // connection pooler (e.g. Supabase pgbouncer on port 6543). Falls
    // back to DATABASE_URL when DIRECT_URL is not set (local dev).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
