-- Migration B: NOT NULL 전환 + 유니크/PK/인덱스 재설계 (백필 후 실행)
BEGIN;
ALTER TABLE "tb_audit_log" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_batch_log" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_bom" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_customer" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_data_history" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_defect" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_defect_dispose" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_demand" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_equip_process" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_equip_status" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_equipment" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_file" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_incoming" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_incoming_dtl" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_inspect_result" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_inspect_result_dtl" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_inspect_std" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_inventory" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_inventory_adjust" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_inventory_tx" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_item" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_lot" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_lot_history" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_maint_plan" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_maint_plan_dtl" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_maint_result" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_maint_result_dtl" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_material_input" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_material_issue" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_material_issue_dtl" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_mold" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_noti_rule" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_notice" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_notification" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_numbering" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_process" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_prod_plan" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_prod_result" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_routing" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_shipment" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_shipment_dtl" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_sys_setting" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_warehouse" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_wo_process" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_wo_worker" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_work_order" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_worker" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_worker_skill" ALTER COLUMN "company_cd" SET NOT NULL;
ALTER TABLE "tb_workshop" ALTER COLUMN "company_cd" SET NOT NULL;
DROP INDEX "tb_defect_defect_no_key";
DROP INDEX "tb_demand_demand_no_key";
DROP INDEX "tb_incoming_incoming_no_key";
DROP INDEX "tb_inspect_result_inspect_no_key";
DROP INDEX "tb_inventory_item_cd_lot_no_wh_cd_key";
DROP INDEX "tb_material_issue_issue_no_key";
DROP INDEX "tb_prod_plan_plan_no_key";
DROP INDEX "tb_shipment_ship_no_key";
DROP INDEX "tb_work_order_wo_no_key";
ALTER TABLE "tb_numbering" DROP CONSTRAINT "tb_numbering_pkey";
ALTER TABLE "tb_numbering" ADD CONSTRAINT "tb_numbering_pkey" PRIMARY KEY ("company_cd", "num_type");
CREATE INDEX "tb_audit_log_company_cd_create_dt_idx" ON "tb_audit_log"("company_cd", "create_dt");
CREATE INDEX "tb_batch_log_company_cd_create_dt_idx" ON "tb_batch_log"("company_cd", "create_dt");
CREATE INDEX "tb_bom_company_cd_create_dt_idx" ON "tb_bom"("company_cd", "create_dt");
CREATE INDEX "tb_customer_company_cd_create_dt_idx" ON "tb_customer"("company_cd", "create_dt");
CREATE INDEX "tb_data_history_company_cd_idx" ON "tb_data_history"("company_cd");
CREATE INDEX "tb_defect_company_cd_create_dt_idx" ON "tb_defect"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_defect_company_cd_defect_no_key" ON "tb_defect"("company_cd", "defect_no");
CREATE INDEX "tb_defect_dispose_company_cd_create_dt_idx" ON "tb_defect_dispose"("company_cd", "create_dt");
CREATE INDEX "tb_demand_company_cd_create_dt_idx" ON "tb_demand"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_demand_company_cd_demand_no_key" ON "tb_demand"("company_cd", "demand_no");
CREATE INDEX "tb_equip_process_company_cd_create_dt_idx" ON "tb_equip_process"("company_cd", "create_dt");
CREATE INDEX "tb_equip_status_company_cd_create_dt_idx" ON "tb_equip_status"("company_cd", "create_dt");
CREATE INDEX "tb_equipment_company_cd_create_dt_idx" ON "tb_equipment"("company_cd", "create_dt");
CREATE INDEX "tb_file_company_cd_create_dt_idx" ON "tb_file"("company_cd", "create_dt");
CREATE INDEX "tb_incoming_company_cd_create_dt_idx" ON "tb_incoming"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_incoming_company_cd_incoming_no_key" ON "tb_incoming"("company_cd", "incoming_no");
CREATE INDEX "tb_incoming_dtl_company_cd_create_dt_idx" ON "tb_incoming_dtl"("company_cd", "create_dt");
CREATE INDEX "tb_inspect_result_company_cd_create_dt_idx" ON "tb_inspect_result"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_inspect_result_company_cd_inspect_no_key" ON "tb_inspect_result"("company_cd", "inspect_no");
CREATE INDEX "tb_inspect_result_dtl_company_cd_create_dt_idx" ON "tb_inspect_result_dtl"("company_cd", "create_dt");
CREATE INDEX "tb_inspect_std_company_cd_create_dt_idx" ON "tb_inspect_std"("company_cd", "create_dt");
CREATE INDEX "tb_inventory_company_cd_create_dt_idx" ON "tb_inventory"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_inventory_company_cd_item_cd_lot_no_wh_cd_key" ON "tb_inventory"("company_cd", "item_cd", "lot_no", "wh_cd");
CREATE INDEX "tb_inventory_adjust_company_cd_create_dt_idx" ON "tb_inventory_adjust"("company_cd", "create_dt");
CREATE INDEX "tb_inventory_tx_company_cd_create_dt_idx" ON "tb_inventory_tx"("company_cd", "create_dt");
CREATE INDEX "tb_item_company_cd_create_dt_idx" ON "tb_item"("company_cd", "create_dt");
CREATE INDEX "tb_lot_company_cd_create_dt_idx" ON "tb_lot"("company_cd", "create_dt");
CREATE INDEX "tb_lot_history_company_cd_create_dt_idx" ON "tb_lot_history"("company_cd", "create_dt");
CREATE INDEX "tb_maint_plan_company_cd_create_dt_idx" ON "tb_maint_plan"("company_cd", "create_dt");
CREATE INDEX "tb_maint_plan_dtl_company_cd_create_dt_idx" ON "tb_maint_plan_dtl"("company_cd", "create_dt");
CREATE INDEX "tb_maint_result_company_cd_create_dt_idx" ON "tb_maint_result"("company_cd", "create_dt");
CREATE INDEX "tb_maint_result_dtl_company_cd_create_dt_idx" ON "tb_maint_result_dtl"("company_cd", "create_dt");
CREATE INDEX "tb_material_input_company_cd_create_dt_idx" ON "tb_material_input"("company_cd", "create_dt");
CREATE INDEX "tb_material_issue_company_cd_create_dt_idx" ON "tb_material_issue"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_material_issue_company_cd_issue_no_key" ON "tb_material_issue"("company_cd", "issue_no");
CREATE INDEX "tb_material_issue_dtl_company_cd_create_dt_idx" ON "tb_material_issue_dtl"("company_cd", "create_dt");
CREATE INDEX "tb_mold_company_cd_create_dt_idx" ON "tb_mold"("company_cd", "create_dt");
CREATE INDEX "tb_noti_rule_company_cd_create_dt_idx" ON "tb_noti_rule"("company_cd", "create_dt");
CREATE INDEX "tb_notice_company_cd_create_dt_idx" ON "tb_notice"("company_cd", "create_dt");
CREATE INDEX "tb_notification_company_cd_create_dt_idx" ON "tb_notification"("company_cd", "create_dt");
CREATE INDEX "tb_numbering_company_cd_create_dt_idx" ON "tb_numbering"("company_cd", "create_dt");
CREATE INDEX "tb_process_company_cd_create_dt_idx" ON "tb_process"("company_cd", "create_dt");
CREATE INDEX "tb_prod_plan_company_cd_create_dt_idx" ON "tb_prod_plan"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_prod_plan_company_cd_plan_no_key" ON "tb_prod_plan"("company_cd", "plan_no");
CREATE INDEX "tb_prod_result_company_cd_create_dt_idx" ON "tb_prod_result"("company_cd", "create_dt");
CREATE INDEX "tb_routing_company_cd_create_dt_idx" ON "tb_routing"("company_cd", "create_dt");
CREATE INDEX "tb_shipment_company_cd_create_dt_idx" ON "tb_shipment"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_shipment_company_cd_ship_no_key" ON "tb_shipment"("company_cd", "ship_no");
CREATE INDEX "tb_shipment_dtl_company_cd_create_dt_idx" ON "tb_shipment_dtl"("company_cd", "create_dt");
CREATE INDEX "tb_sys_setting_company_cd_create_dt_idx" ON "tb_sys_setting"("company_cd", "create_dt");
CREATE INDEX "tb_warehouse_company_cd_create_dt_idx" ON "tb_warehouse"("company_cd", "create_dt");
CREATE INDEX "tb_wo_process_company_cd_create_dt_idx" ON "tb_wo_process"("company_cd", "create_dt");
CREATE INDEX "tb_wo_worker_company_cd_create_dt_idx" ON "tb_wo_worker"("company_cd", "create_dt");
CREATE INDEX "tb_work_order_company_cd_create_dt_idx" ON "tb_work_order"("company_cd", "create_dt");
CREATE UNIQUE INDEX "tb_work_order_company_cd_wo_no_key" ON "tb_work_order"("company_cd", "wo_no");
CREATE INDEX "tb_worker_company_cd_create_dt_idx" ON "tb_worker"("company_cd", "create_dt");
CREATE INDEX "tb_worker_skill_company_cd_create_dt_idx" ON "tb_worker_skill"("company_cd", "create_dt");
CREATE INDEX "tb_workshop_company_cd_create_dt_idx" ON "tb_workshop"("company_cd", "create_dt");
ALTER TABLE "tb_audit_log" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_batch_log" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_bom" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_customer" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_data_history" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_defect" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_defect_dispose" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_demand" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_equip_process" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_equip_status" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_equipment" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_file" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_incoming" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_incoming_dtl" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_inspect_result" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_inspect_result_dtl" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_inspect_std" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_inventory" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_inventory_adjust" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_inventory_tx" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_item" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_lot" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_lot_history" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_maint_plan" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_maint_plan_dtl" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_maint_result" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_maint_result_dtl" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_material_input" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_material_issue" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_material_issue_dtl" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_mold" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_noti_rule" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_notice" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_notification" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_numbering" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_process" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_prod_plan" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_prod_result" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_routing" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_shipment" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_shipment_dtl" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_sys_setting" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_warehouse" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_wo_process" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_wo_worker" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_work_order" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_worker" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_worker_skill" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_workshop" ALTER COLUMN "company_cd" SET DEFAULT '';
ALTER TABLE "tb_audit_log" ADD CONSTRAINT "tb_audit_log_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_batch_log" ADD CONSTRAINT "tb_batch_log_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_bom" ADD CONSTRAINT "tb_bom_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_customer" ADD CONSTRAINT "tb_customer_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_data_history" ADD CONSTRAINT "tb_data_history_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_defect" ADD CONSTRAINT "tb_defect_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_defect_dispose" ADD CONSTRAINT "tb_defect_dispose_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_demand" ADD CONSTRAINT "tb_demand_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_equip_process" ADD CONSTRAINT "tb_equip_process_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_equip_status" ADD CONSTRAINT "tb_equip_status_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_equipment" ADD CONSTRAINT "tb_equipment_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_file" ADD CONSTRAINT "tb_file_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_incoming" ADD CONSTRAINT "tb_incoming_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_incoming_dtl" ADD CONSTRAINT "tb_incoming_dtl_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_inspect_result" ADD CONSTRAINT "tb_inspect_result_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_inspect_result_dtl" ADD CONSTRAINT "tb_inspect_result_dtl_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_inspect_std" ADD CONSTRAINT "tb_inspect_std_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_inventory" ADD CONSTRAINT "tb_inventory_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_inventory_adjust" ADD CONSTRAINT "tb_inventory_adjust_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_inventory_tx" ADD CONSTRAINT "tb_inventory_tx_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_item" ADD CONSTRAINT "tb_item_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_lot" ADD CONSTRAINT "tb_lot_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_lot_history" ADD CONSTRAINT "tb_lot_history_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_maint_plan" ADD CONSTRAINT "tb_maint_plan_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_maint_plan_dtl" ADD CONSTRAINT "tb_maint_plan_dtl_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_maint_result" ADD CONSTRAINT "tb_maint_result_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_maint_result_dtl" ADD CONSTRAINT "tb_maint_result_dtl_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_material_input" ADD CONSTRAINT "tb_material_input_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_material_issue" ADD CONSTRAINT "tb_material_issue_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_material_issue_dtl" ADD CONSTRAINT "tb_material_issue_dtl_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_mold" ADD CONSTRAINT "tb_mold_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_noti_rule" ADD CONSTRAINT "tb_noti_rule_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_notice" ADD CONSTRAINT "tb_notice_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_notification" ADD CONSTRAINT "tb_notification_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_numbering" ADD CONSTRAINT "tb_numbering_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_process" ADD CONSTRAINT "tb_process_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_prod_plan" ADD CONSTRAINT "tb_prod_plan_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_prod_result" ADD CONSTRAINT "tb_prod_result_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_routing" ADD CONSTRAINT "tb_routing_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_shipment" ADD CONSTRAINT "tb_shipment_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_shipment_dtl" ADD CONSTRAINT "tb_shipment_dtl_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_sys_setting" ADD CONSTRAINT "tb_sys_setting_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_warehouse" ADD CONSTRAINT "tb_warehouse_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_wo_process" ADD CONSTRAINT "tb_wo_process_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_wo_worker" ADD CONSTRAINT "tb_wo_worker_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_work_order" ADD CONSTRAINT "tb_work_order_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_worker" ADD CONSTRAINT "tb_worker_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_worker_skill" ADD CONSTRAINT "tb_worker_skill_company_cd_not_empty" CHECK (company_cd <> '');
ALTER TABLE "tb_workshop" ADD CONSTRAINT "tb_workshop_company_cd_not_empty" CHECK (company_cd <> '');
COMMIT;
