-- Rollback: Migration B → A 역순 (신규 테넌트 데이터 입력 전까지만 안전)
BEGIN;
ALTER TABLE "tb_audit_log" DROP CONSTRAINT IF EXISTS "tb_audit_log_company_cd_not_empty";
ALTER TABLE "tb_batch_log" DROP CONSTRAINT IF EXISTS "tb_batch_log_company_cd_not_empty";
ALTER TABLE "tb_bom" DROP CONSTRAINT IF EXISTS "tb_bom_company_cd_not_empty";
ALTER TABLE "tb_customer" DROP CONSTRAINT IF EXISTS "tb_customer_company_cd_not_empty";
ALTER TABLE "tb_data_history" DROP CONSTRAINT IF EXISTS "tb_data_history_company_cd_not_empty";
ALTER TABLE "tb_defect" DROP CONSTRAINT IF EXISTS "tb_defect_company_cd_not_empty";
ALTER TABLE "tb_defect_dispose" DROP CONSTRAINT IF EXISTS "tb_defect_dispose_company_cd_not_empty";
ALTER TABLE "tb_demand" DROP CONSTRAINT IF EXISTS "tb_demand_company_cd_not_empty";
ALTER TABLE "tb_equip_process" DROP CONSTRAINT IF EXISTS "tb_equip_process_company_cd_not_empty";
ALTER TABLE "tb_equip_status" DROP CONSTRAINT IF EXISTS "tb_equip_status_company_cd_not_empty";
ALTER TABLE "tb_equipment" DROP CONSTRAINT IF EXISTS "tb_equipment_company_cd_not_empty";
ALTER TABLE "tb_file" DROP CONSTRAINT IF EXISTS "tb_file_company_cd_not_empty";
ALTER TABLE "tb_incoming" DROP CONSTRAINT IF EXISTS "tb_incoming_company_cd_not_empty";
ALTER TABLE "tb_incoming_dtl" DROP CONSTRAINT IF EXISTS "tb_incoming_dtl_company_cd_not_empty";
ALTER TABLE "tb_inspect_result" DROP CONSTRAINT IF EXISTS "tb_inspect_result_company_cd_not_empty";
ALTER TABLE "tb_inspect_result_dtl" DROP CONSTRAINT IF EXISTS "tb_inspect_result_dtl_company_cd_not_empty";
ALTER TABLE "tb_inspect_std" DROP CONSTRAINT IF EXISTS "tb_inspect_std_company_cd_not_empty";
ALTER TABLE "tb_inventory" DROP CONSTRAINT IF EXISTS "tb_inventory_company_cd_not_empty";
ALTER TABLE "tb_inventory_adjust" DROP CONSTRAINT IF EXISTS "tb_inventory_adjust_company_cd_not_empty";
ALTER TABLE "tb_inventory_tx" DROP CONSTRAINT IF EXISTS "tb_inventory_tx_company_cd_not_empty";
ALTER TABLE "tb_item" DROP CONSTRAINT IF EXISTS "tb_item_company_cd_not_empty";
ALTER TABLE "tb_lot" DROP CONSTRAINT IF EXISTS "tb_lot_company_cd_not_empty";
ALTER TABLE "tb_lot_history" DROP CONSTRAINT IF EXISTS "tb_lot_history_company_cd_not_empty";
ALTER TABLE "tb_maint_plan" DROP CONSTRAINT IF EXISTS "tb_maint_plan_company_cd_not_empty";
ALTER TABLE "tb_maint_plan_dtl" DROP CONSTRAINT IF EXISTS "tb_maint_plan_dtl_company_cd_not_empty";
ALTER TABLE "tb_maint_result" DROP CONSTRAINT IF EXISTS "tb_maint_result_company_cd_not_empty";
ALTER TABLE "tb_maint_result_dtl" DROP CONSTRAINT IF EXISTS "tb_maint_result_dtl_company_cd_not_empty";
ALTER TABLE "tb_material_input" DROP CONSTRAINT IF EXISTS "tb_material_input_company_cd_not_empty";
ALTER TABLE "tb_material_issue" DROP CONSTRAINT IF EXISTS "tb_material_issue_company_cd_not_empty";
ALTER TABLE "tb_material_issue_dtl" DROP CONSTRAINT IF EXISTS "tb_material_issue_dtl_company_cd_not_empty";
ALTER TABLE "tb_mold" DROP CONSTRAINT IF EXISTS "tb_mold_company_cd_not_empty";
ALTER TABLE "tb_noti_rule" DROP CONSTRAINT IF EXISTS "tb_noti_rule_company_cd_not_empty";
ALTER TABLE "tb_notice" DROP CONSTRAINT IF EXISTS "tb_notice_company_cd_not_empty";
ALTER TABLE "tb_notification" DROP CONSTRAINT IF EXISTS "tb_notification_company_cd_not_empty";
ALTER TABLE "tb_numbering" DROP CONSTRAINT IF EXISTS "tb_numbering_company_cd_not_empty";
ALTER TABLE "tb_process" DROP CONSTRAINT IF EXISTS "tb_process_company_cd_not_empty";
ALTER TABLE "tb_prod_plan" DROP CONSTRAINT IF EXISTS "tb_prod_plan_company_cd_not_empty";
ALTER TABLE "tb_prod_result" DROP CONSTRAINT IF EXISTS "tb_prod_result_company_cd_not_empty";
ALTER TABLE "tb_routing" DROP CONSTRAINT IF EXISTS "tb_routing_company_cd_not_empty";
ALTER TABLE "tb_shipment" DROP CONSTRAINT IF EXISTS "tb_shipment_company_cd_not_empty";
ALTER TABLE "tb_shipment_dtl" DROP CONSTRAINT IF EXISTS "tb_shipment_dtl_company_cd_not_empty";
ALTER TABLE "tb_sys_setting" DROP CONSTRAINT IF EXISTS "tb_sys_setting_company_cd_not_empty";
ALTER TABLE "tb_warehouse" DROP CONSTRAINT IF EXISTS "tb_warehouse_company_cd_not_empty";
ALTER TABLE "tb_wo_process" DROP CONSTRAINT IF EXISTS "tb_wo_process_company_cd_not_empty";
ALTER TABLE "tb_wo_worker" DROP CONSTRAINT IF EXISTS "tb_wo_worker_company_cd_not_empty";
ALTER TABLE "tb_work_order" DROP CONSTRAINT IF EXISTS "tb_work_order_company_cd_not_empty";
ALTER TABLE "tb_worker" DROP CONSTRAINT IF EXISTS "tb_worker_company_cd_not_empty";
ALTER TABLE "tb_worker_skill" DROP CONSTRAINT IF EXISTS "tb_worker_skill_company_cd_not_empty";
ALTER TABLE "tb_workshop" DROP CONSTRAINT IF EXISTS "tb_workshop_company_cd_not_empty";
DROP INDEX IF EXISTS "tb_audit_log_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_batch_log_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_bom_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_customer_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_data_history_company_cd_idx";
DROP INDEX IF EXISTS "tb_defect_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_defect_company_cd_defect_no_key";
DROP INDEX IF EXISTS "tb_defect_dispose_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_demand_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_demand_company_cd_demand_no_key";
DROP INDEX IF EXISTS "tb_equip_process_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_equip_status_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_equipment_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_file_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_incoming_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_incoming_company_cd_incoming_no_key";
DROP INDEX IF EXISTS "tb_incoming_dtl_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_inspect_result_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_inspect_result_company_cd_inspect_no_key";
DROP INDEX IF EXISTS "tb_inspect_result_dtl_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_inspect_std_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_inventory_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_inventory_company_cd_item_cd_lot_no_wh_cd_key";
DROP INDEX IF EXISTS "tb_inventory_adjust_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_inventory_tx_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_item_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_lot_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_lot_history_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_maint_plan_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_maint_plan_dtl_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_maint_result_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_maint_result_dtl_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_material_input_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_material_issue_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_material_issue_company_cd_issue_no_key";
DROP INDEX IF EXISTS "tb_material_issue_dtl_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_mold_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_noti_rule_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_notice_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_notification_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_numbering_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_process_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_prod_plan_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_prod_plan_company_cd_plan_no_key";
DROP INDEX IF EXISTS "tb_prod_result_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_routing_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_shipment_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_shipment_company_cd_ship_no_key";
DROP INDEX IF EXISTS "tb_shipment_dtl_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_sys_setting_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_warehouse_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_wo_process_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_wo_worker_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_work_order_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_work_order_company_cd_wo_no_key";
DROP INDEX IF EXISTS "tb_worker_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_worker_skill_company_cd_create_dt_idx";
DROP INDEX IF EXISTS "tb_workshop_company_cd_create_dt_idx";
ALTER TABLE "tb_numbering" DROP CONSTRAINT "tb_numbering_pkey";
ALTER TABLE "tb_numbering" ADD CONSTRAINT "tb_numbering_pkey" PRIMARY KEY ("num_type");
CREATE UNIQUE INDEX "tb_defect_defect_no_key" ON "tb_defect"("defect_no");
CREATE UNIQUE INDEX "tb_demand_demand_no_key" ON "tb_demand"("demand_no");
CREATE UNIQUE INDEX "tb_incoming_incoming_no_key" ON "tb_incoming"("incoming_no");
CREATE UNIQUE INDEX "tb_inspect_result_inspect_no_key" ON "tb_inspect_result"("inspect_no");
CREATE UNIQUE INDEX "tb_material_issue_issue_no_key" ON "tb_material_issue"("issue_no");
CREATE UNIQUE INDEX "tb_prod_plan_plan_no_key" ON "tb_prod_plan"("plan_no");
CREATE UNIQUE INDEX "tb_shipment_ship_no_key" ON "tb_shipment"("ship_no");
CREATE UNIQUE INDEX "tb_work_order_wo_no_key" ON "tb_work_order"("wo_no");
CREATE UNIQUE INDEX "tb_inventory_item_cd_lot_no_wh_cd_key" ON "tb_inventory"("item_cd", "lot_no", "wh_cd");
ALTER TABLE "tb_audit_log" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_batch_log" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_bom" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_customer" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_data_history" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_defect" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_defect_dispose" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_demand" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_equip_process" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_equip_status" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_equipment" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_file" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_incoming" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_incoming_dtl" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_inspect_result" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_inspect_result_dtl" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_inspect_std" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_inventory" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_inventory_adjust" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_inventory_tx" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_item" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_lot" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_lot_history" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_maint_plan" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_maint_plan_dtl" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_maint_result" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_maint_result_dtl" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_material_input" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_material_issue" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_material_issue_dtl" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_mold" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_noti_rule" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_notice" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_notification" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_numbering" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_process" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_prod_plan" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_prod_result" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_routing" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_shipment" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_shipment_dtl" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_sys_setting" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_warehouse" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_wo_process" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_wo_worker" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_work_order" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_worker" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_worker_skill" DROP COLUMN IF EXISTS "company_cd";
ALTER TABLE "tb_workshop" DROP COLUMN IF EXISTS "company_cd";
COMMIT;
